using RPL.Core.Entities;
using RPL.Core.Result;
using System.Threading.Tasks;

namespace RPL.Infrastructure.Services.Interfaces
{
    public interface IUserService
    {
        Task<Result<ApplicationUser>> CreateUserAsync(ApplicationUser user, string autoGeneratedPassword, string role);
    }
}
