using Ardalis.Result;
using RPL.Core.Entities;
using System.Threading.Tasks;

namespace RPL.Core.Interfaces
{
    public interface IUserService
    {
        Task<Result<ApplicationUser>> CreateUserAsync(ApplicationUser user, string autoGeneratedPassword, string role);

        Task<Result<string>> VerifyUserPhoneNumberAsync(string phoneNumber, string verificationCode);
    }
}
